services:
  - docker

before_install:
  - docker build -t zimbbra .
  - docker run -d -p 0.0.0.0:80:8080 zimbra
  - docker ps -a

deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
 
